---
- hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start service Nginx
      service:
        name: nginx
        state: started
